### ISSUE TITLE
Is the evaluation code available?

### ISSUE THREAD

**Issue by ibraheem-moosa** [rajaswa/indic-syntax-evaluation#10]
Hi. We would like to evaluate our models on this dataset. Is the evaluation code for your paper available?

**Comment by rajaswa** [comment]
Hi @ibraheem-moosa. 👋  Yes, the evaluation code is available. ✔️  But it might take some time for us to clean and push it here. I will try to push it by this weekend. 😄

**Comment by rajaswa** [comment]
Hi @ibraheem-moosa, you can find the evaluation code for all the 4 tasks here: https://github.com/rajaswa/indic-syntax-evaluation/tree/main/notebooks

These notebooks are by default set to work with the IndicBERT model. But you can easily change the parameters to make it work for any model available on Hugging Face, different seeds, and layers.
